# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pcc/gwfa6/gwfa5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pcc/gwfa6/gwfa5/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pcc/gwfa6/gwfa5/build/CMakeFiles /home/pcc/gwfa6/gwfa5/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pcc/gwfa6/gwfa5/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gwf-test

# Build rule for target.
gwf-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gwf-test
.PHONY : gwf-test

# fast build rule for target.
gwf-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/build
.PHONY : gwf-test/fast

gfa-base.o: gfa-base.c.o
.PHONY : gfa-base.o

# target to build an object file
gfa-base.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gfa-base.c.o
.PHONY : gfa-base.c.o

gfa-base.i: gfa-base.c.i
.PHONY : gfa-base.i

# target to preprocess a source file
gfa-base.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gfa-base.c.i
.PHONY : gfa-base.c.i

gfa-base.s: gfa-base.c.s
.PHONY : gfa-base.s

# target to generate assembly for a file
gfa-base.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gfa-base.c.s
.PHONY : gfa-base.c.s

gfa-io.o: gfa-io.c.o
.PHONY : gfa-io.o

# target to build an object file
gfa-io.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gfa-io.c.o
.PHONY : gfa-io.c.o

gfa-io.i: gfa-io.c.i
.PHONY : gfa-io.i

# target to preprocess a source file
gfa-io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gfa-io.c.i
.PHONY : gfa-io.c.i

gfa-io.s: gfa-io.c.s
.PHONY : gfa-io.s

# target to generate assembly for a file
gfa-io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gfa-io.c.s
.PHONY : gfa-io.c.s

gfa-sub.o: gfa-sub.c.o
.PHONY : gfa-sub.o

# target to build an object file
gfa-sub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gfa-sub.c.o
.PHONY : gfa-sub.c.o

gfa-sub.i: gfa-sub.c.i
.PHONY : gfa-sub.i

# target to preprocess a source file
gfa-sub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gfa-sub.c.i
.PHONY : gfa-sub.c.i

gfa-sub.s: gfa-sub.c.s
.PHONY : gfa-sub.s

# target to generate assembly for a file
gfa-sub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gfa-sub.c.s
.PHONY : gfa-sub.c.s

gwf-ed.o: gwf-ed.c.o
.PHONY : gwf-ed.o

# target to build an object file
gwf-ed.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gwf-ed.c.o
.PHONY : gwf-ed.c.o

gwf-ed.i: gwf-ed.c.i
.PHONY : gwf-ed.i

# target to preprocess a source file
gwf-ed.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gwf-ed.c.i
.PHONY : gwf-ed.c.i

gwf-ed.s: gwf-ed.c.s
.PHONY : gwf-ed.s

# target to generate assembly for a file
gwf-ed.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/gwf-ed.c.s
.PHONY : gwf-ed.c.s

kalloc.o: kalloc.c.o
.PHONY : kalloc.o

# target to build an object file
kalloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/kalloc.c.o
.PHONY : kalloc.c.o

kalloc.i: kalloc.c.i
.PHONY : kalloc.i

# target to preprocess a source file
kalloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/kalloc.c.i
.PHONY : kalloc.c.i

kalloc.s: kalloc.c.s
.PHONY : kalloc.s

# target to generate assembly for a file
kalloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/kalloc.c.s
.PHONY : kalloc.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gwf-test.dir/build.make CMakeFiles/gwf-test.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gwf-test"
	@echo "... gfa-base.o"
	@echo "... gfa-base.i"
	@echo "... gfa-base.s"
	@echo "... gfa-io.o"
	@echo "... gfa-io.i"
	@echo "... gfa-io.s"
	@echo "... gfa-sub.o"
	@echo "... gfa-sub.i"
	@echo "... gfa-sub.s"
	@echo "... gwf-ed.o"
	@echo "... gwf-ed.i"
	@echo "... gwf-ed.s"
	@echo "... kalloc.o"
	@echo "... kalloc.i"
	@echo "... kalloc.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

